"""add insights table (Cortex Insights)

Revision ID: 27fe7022dc62
Revises: 8b1354471d93
Create Date: 2026-06-17 18:32:25.233838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fe7022dc62'
down_revision: Union[str, Sequence[str], None] = '8b1354471d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('impact', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='insightimpact'), nullable=False),
    sa.Column('effort', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='insighteffort'), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('quadrant', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED', name='insightstatus'), nullable=False),
    sa.Column('is_critical_alarm', sa.Boolean(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('FINDING', 'RISK', 'DIAGNOSIS', 'MANUAL', name='insightsource'), nullable=False),
    sa.Column('source_ref', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_organization_id'), 'insights', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_organization_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    # Drop the Postgres enum types the table created (no-op on SQLite).
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name in ('insightimpact', 'insighteffort', 'insightstatus', 'insightsource'):
            op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
