"""initial schema

Revision ID: 8b1354471d93
Revises: 
Create Date: 2026-06-09 18:59:56.804063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1354471d93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpis_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpis_organization_id'), ['organization_id'], unique=False)

    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_modules_id'), ['id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('organization_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('toolkit_toolkits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_toolkits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_toolkits_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('clevel_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('syner_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DEFERRED', 'NEEDS_MORE_INFO', name='decisionstatus'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clevel_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clevel_decisions_id'), ['id'], unique=False)

    op.create_table('clevel_engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='engagementstatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clevel_engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clevel_engagements_id'), ['id'], unique=False)

    op.create_table('clevel_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('probability', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'MITIGATING', 'MONITORING', 'CLOSED', name='riskstatus'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clevel_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clevel_risks_id'), ['id'], unique=False)

    op.create_table('organization_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_modules_id'), ['id'], unique=False)

    op.create_table('organization_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_users_id'), ['id'], unique=False)

    op.create_table('survey_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_surveys_id'), ['id'], unique=False)

    op.create_table('toolkit_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolkit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['toolkit_id'], ['toolkit_toolkits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_tools_id'), ['id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_id'), ['id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_id'), ['id'], unique=False)

    op.create_table('clevel_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['clevel_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clevel_deliverables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clevel_deliverables_id'), ['id'], unique=False)

    op.create_table('clevel_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='findingcriticality'), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['clevel_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clevel_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clevel_findings_id'), ['id'], unique=False)

    op.create_table('clevel_initiatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'PROPOSED', 'APPROVED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', name='initiativestatus'), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('estimated_budget', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['clevel_engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clevel_initiatives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clevel_initiatives_id'), ['id'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('survey_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('public_token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='campaignstatus'), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('collect_email', sa.Boolean(), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('max_responses', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_surveys.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_campaigns_public_token'), ['public_token'], unique=True)

    op.create_table('survey_diagnostic_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_diagnostic_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_diagnostic_rules_id'), ['id'], unique=False)

    op.create_table('survey_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_sections_id'), ['id'], unique=False)

    op.create_table('toolkit_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'AI_GENERATED', 'CONSULTANT_REVIEW', 'APPROVED', 'CLIENT_SHARED', 'ARCHIVED', name='toolrunstatus'), nullable=True),
    sa.Column('visibility', sa.Enum('INTERNAL_ONLY', 'CLIENT_SHARED', 'CLIENT_UPLOAD', 'DRAFT_INTERNAL', 'APPROVED', 'CLIENT_VISIBLE', name='visibility'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['toolkit_tools.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_runs_id'), ['id'], unique=False)

    op.create_table('toolkit_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('json_schema_output', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['toolkit_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_templates_id'), ['id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)

    op.create_table('diagnosis_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('swot_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_dimensions_id'), ['id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_id'), ['id'], unique=False)

    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_id'), ['id'], unique=False)

    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'LINEAR_SCALE', 'OPEN_TEXT', name='surveyquestiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('scale_min_label', sa.String(), nullable=True),
    sa.Column('scale_max_label', sa.String(), nullable=True),
    sa.Column('diagnostic_use', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['survey_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_questions_id'), ['id'], unique=False)

    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('respondent_email', sa.String(), nullable=True),
    sa.Column('respondent_name', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['survey_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_responses_id'), ['id'], unique=False)

    op.create_table('toolkit_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('exported_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['toolkit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_exports_id'), ['id'], unique=False)

    op.create_table('toolkit_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['toolkit_runs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_inputs_id'), ['id'], unique=False)

    op.create_table('toolkit_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['toolkit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_outputs_id'), ['id'], unique=False)

    op.create_table('toolkit_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_converted_to_roadmap', sa.Boolean(), nullable=True),
    sa.Column('roadmap_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['toolkit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_recommendations_id'), ['id'], unique=False)

    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_items_id'), ['id'], unique=False)

    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Integer(), nullable=True),
    sa.Column('value_options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_answers_id'), ['id'], unique=False)

    op.create_table('toolkit_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['toolkit_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolkit_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolkit_evidence_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_evidence_id'))

    op.drop_table('toolkit_evidence')
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_answers_id'))

    op.drop_table('survey_answers')
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_items_id'))

    op.drop_table('roadmap_items')
    with op.batch_alter_table('toolkit_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_recommendations_id'))

    op.drop_table('toolkit_recommendations')
    with op.batch_alter_table('toolkit_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_outputs_id'))

    op.drop_table('toolkit_outputs')
    with op.batch_alter_table('toolkit_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_inputs_id'))

    op.drop_table('toolkit_inputs')
    with op.batch_alter_table('toolkit_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_exports_id'))

    op.drop_table('toolkit_exports')
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_id'))

    op.drop_table('survey_responses')
    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_questions_id'))

    op.drop_table('survey_questions')
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_id'))

    op.drop_table('roadmaps')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('diagnosis_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_dimensions_id'))

    op.drop_table('diagnosis_dimensions')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('toolkit_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_templates_id'))

    op.drop_table('toolkit_templates')
    with op.batch_alter_table('toolkit_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_runs_id'))

    op.drop_table('toolkit_runs')
    with op.batch_alter_table('survey_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_sections_id'))

    op.drop_table('survey_sections')
    with op.batch_alter_table('survey_diagnostic_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_diagnostic_rules_id'))

    op.drop_table('survey_diagnostic_rules')
    with op.batch_alter_table('survey_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_campaigns_public_token'))
        batch_op.drop_index(batch_op.f('ix_survey_campaigns_id'))

    op.drop_table('survey_campaigns')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_id'))

    op.drop_table('diagnoses')
    with op.batch_alter_table('clevel_initiatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clevel_initiatives_id'))

    op.drop_table('clevel_initiatives')
    with op.batch_alter_table('clevel_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clevel_findings_id'))

    op.drop_table('clevel_findings')
    with op.batch_alter_table('clevel_deliverables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clevel_deliverables_id'))

    op.drop_table('clevel_deliverables')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('toolkit_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_tools_id'))

    op.drop_table('toolkit_tools')
    with op.batch_alter_table('survey_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_surveys_id'))

    op.drop_table('survey_surveys')
    with op.batch_alter_table('organization_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_users_id'))

    op.drop_table('organization_users')
    with op.batch_alter_table('organization_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_modules_id'))

    op.drop_table('organization_modules')
    with op.batch_alter_table('clevel_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clevel_risks_id'))

    op.drop_table('clevel_risks')
    with op.batch_alter_table('clevel_engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clevel_engagements_id'))

    op.drop_table('clevel_engagements')
    with op.batch_alter_table('clevel_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clevel_decisions_id'))

    op.drop_table('clevel_decisions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('toolkit_toolkits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolkit_toolkits_id'))

    op.drop_table('toolkit_toolkits')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_id'))
        batch_op.drop_index(batch_op.f('ix_modules_code'))

    op.drop_table('modules')
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpis_organization_id'))
        batch_op.drop_index(batch_op.f('ix_kpis_id'))

    op.drop_table('kpis')
    # ### end Alembic commands ###
