"""PR3: report, recommendation, workspace_user, comment + document.uploaded_by

Revision ID: d78fbf94439d
Revises: b7f3a9c1d2e4
Create Date: 2026-06-19 17:43:47.317536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78fbf94439d'
down_revision: Union[str, Sequence[str], None] = 'b7f3a9c1d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index('ix_comments_object', 'comments', ['object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_comments_object_id'), 'comments', ['object_id'], unique=False)
    op.create_index(op.f('ix_comments_organization_id'), 'comments', ['organization_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT_INTERNAL', 'CONSULTANT_REVIEW', 'APPROVED', 'CLIENT_SHARED', 'ARCHIVED', name='reportstatus'), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_table('workspace_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_role', sa.String(), nullable=False),
    sa.Column('visibility_scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_index(op.f('ix_workspace_users_id'), 'workspace_users', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_users_user_id'), 'workspace_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_users_workspace_id'), 'workspace_users', ['workspace_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('INTERNAL', 'SHARED', 'EXECUTIVE_ONLY', 'TASK_VISIBLE', name='recvisibility'), nullable=False),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('linked_roadmap_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_roadmap_item_id'], ['roadmap_items.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recommendations_workspace_id'), 'recommendations', ['workspace_id'], unique=False)
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_foreign_key('fk_documents_uploaded_by_users', 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_uploaded_by_users', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_column('documents', 'uploaded_by')
    op.drop_index(op.f('ix_recommendations_workspace_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_workspace_users_workspace_id'), table_name='workspace_users')
    op.drop_index(op.f('ix_workspace_users_user_id'), table_name='workspace_users')
    op.drop_index(op.f('ix_workspace_users_id'), table_name='workspace_users')
    op.drop_table('workspace_users')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_comments_organization_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_object_id'), table_name='comments')
    op.drop_index('ix_comments_object', table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # Drop the Postgres enum types these tables created (no-op on SQLite).
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name in ('reportstatus', 'recvisibility'):
            op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
